development:
  dialect: postgres
  database: golangflow_development
  user: postgres
  password: postgres
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/golangflow_test?sslmode=disable"}}

staging:
  url: {{env "STAGE_DATABASE_URL"}}
  dialect: postgres
  pool: 1
  idle_pool: 1S

production:
  url: {{env "DATABASE_URL"}}
  dialect: postgres
  pool: 1
  idle_pool: 1S