
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/gobuffalo/buffalo"
  version = "0.14.8"

[[constraint]]
  name = "github.com/gobuffalo/envy"
  version = "1.6.1"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "1.10.6"

[[constraint]]
  name = "github.com/gobuffalo/plush"
  version = "3.6.7"

[[constraint]]
  branch = "master"
  name = "github.com/gobuffalo/suite"

[[constraint]]
  name = "github.com/gobuffalo/tags"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/gorilla/feeds"

[[constraint]]
  name = "github.com/markbates/goth"
  version = "1.42.0"

[[constraint]]
  branch = "master"
  name = "github.com/markbates/grift"

[[constraint]]
  name = "github.com/gobuffalo/pop"
  version = "4.2.2"

[[constraint]]
  version = "v2.0.0"
  name = "github.com/gobuffalo/validate"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/gobuffalo/uuid"
  version = "v2.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  branch = "master"
  name = "github.com/writeas/go-strip-markdown"

[[constraint]]
  name = "github.com/newrelic/go-agent"
  version = "1.11.0"

[[constraint]]
  branch = "master"
  name = "github.com/heroku/x"

[[constraint]]
  branch = "master"
  name = "github.com/bscott/googl"

[[constraint]]
  branch = "master"
  name = "github.com/dghubble/go-twitter"

[[constraint]]
  name = "github.com/dghubble/oauth1"
  version = "0.4.0"
